services:
  shell:
    build: ./shell-mfe
    container_name: shell
    ports:
      - "3000:4173"
    depends_on:
      - auth
      - order
      - quotation
      - tracking

  auth:
    build: ./auth-mfe
    container_name: auth
    ports:
      - "3001:4173"

  order:
    build: ./order-mfe
    container_name: order
    ports:
      - "3002:4173"

  quotation:
    build: ./quotation-mfe
    container_name: quotation
    ports:
      - "3003:4173"
  tracking:
    build: ./tracking-mfe
    container_name: tracking
    ports:
      - "3004:4173"
